language: 'java'

cache:
  directories:
    - '${HOME}/.m2/repository'
    - '${HOME}/downloads'

before_cache:
  - 'mvn -q -fn org.codehaus.mojo:build-helper-maven-plugin:3.2.0:remove-project-artifact -Dbuildhelper.removeAll=false -Dbuildhelper.failOnError=false'

env:
  global:
    - MAVEN_BUILD_OPTIONS: '"-Dorg.slf4j.simpleLogger.log.org.apache.maven.cli.transfer.Slf4jMavenTransferListener=warn"'
    - MAVEN_WRAPPER: '0'
    - COVERAGE_BUILD: '0'
    - COPILOT_BUILD: '0'
    - CURL_CONNECT_TIMEOUT: '300'
    - CURL_MAX_TIME: '1800'
    - CURL_RETRY: '10'
    - CURL_RETRY_DELAY: '10'
    - DEPENDENCIES_HOME: '${HOME}/dependencies'
    - DOWNLOADS_HOME: '${HOME}/downloads'

matrix:
  include:
    # OpenJDK 8
    - dist: 'bionic'
      jdk: 'openjdk8'
      env:
        COPILOT_BUILD: '1'

install: 'source ./travis/install.sh'

script: 'source ./travis/build.sh'
